version: '3.7'
services:
  mongo:
    image: mongo:4.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mongo

volumes:
  database:
